import type { APIRoute } from 'astro';
import { authorisedOrder, json } from '../../../lib/safework/orders.mjs';
export const prerender = false;
const escapeHtml=(value:unknown)=>String(value??'').replace(/[&<>"']/g,(character)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[character]||character));
export const GET: APIRoute = async ({request,locals}) => {
 const order=await authorisedOrder(request,locals.runtime.env.FULFILMENT_DB);
 if(!order || order.status!=='ready') return json({error:'Your document is not available yet.'},404);
 let company='customer';
 try { company=JSON.parse(order.input_json).company || company; } catch {}
 const slug=String(company).normalize('NFKD').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48) || 'customer';
 const filename=`SafeWork-${slug}-${String(order.id).slice(0,8)}.html`;
 let document=String(order.document_html);
 if(order.approval_json){const approval=JSON.parse(order.approval_json);const signedAt=new Intl.DateTimeFormat('en-GB',{dateStyle:'long',timeStyle:'short',timeZone:'Europe/London'}).format(new Date(approval.signedAt));const workerRows=approval.workers.map((name:string,index:number)=>`<tr><td>${index+1}</td><td>${escapeHtml(name)}</td><td>Typed acknowledgement</td><td>${escapeHtml(signedAt)}</td></tr>`).join('');const audit=`<section class="sheet permit-sheet"><header><span>DIGITAL SIGN-OFF</span><strong>Locked approval and workforce acknowledgement</strong></header><main><div class="permit-callout"><strong>PACK REVIEWED AND DIGITALLY APPROVED</strong><p>Recorded against order ${escapeHtml(String(order.id).slice(0,8))} at ${escapeHtml(signedAt)}.</p></div><h2>Supervisor declaration</h2><p>I confirm that I reviewed this work pack against the actual job and site information, made any necessary amendments before approval, and briefed the named workforce on the work sequence, hazards, controls, permits and emergency arrangements.</p><table><thead><tr><th>Approving supervisor</th><th>Role</th><th>Signature method</th><th>Date / time</th></tr></thead><tbody><tr><td>${escapeHtml(approval.supervisorName)}</td><td>${escapeHtml(approval.supervisorRole)}</td><td>Typed digital approval</td><td>${escapeHtml(signedAt)}</td></tr></tbody></table><h2>Workforce acknowledgement</h2><table><thead><tr><th>No.</th><th>Worker name</th><th>Acknowledgement</th><th>Date / time</th></tr></thead><tbody>${workerRows}</tbody></table><div class="warning">This audit sheet records the declarations made through the private order page. It does not independently verify identity, competence or site conditions.</div></main><footer><span>SafeWork AI — locked digital sign-off</span><span class="company-watermark">${escapeHtml(company)} · ${escapeHtml(new Date(approval.signedAt).toLocaleDateString('en-GB'))}</span><span>Digital sign-off</span></footer></section>`;document=document.replace('</body>',audit+'</body>');}
 return new Response(document,{headers:{'Content-Type':'text/html; charset=utf-8','Content-Disposition':`attachment; filename="${filename}"`,'X-SafeWork-Filename':filename,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'none'; style-src 'unsafe-inline'; img-src data:; sandbox allow-modals"}});
};
